### ISSUE TITLE
Filter Widget

### ISSUE THREAD

**Issue by stdavis** [agrc/wfrc-wab-widgets#20]
![image](https://user-images.githubusercontent.com/1326248/49296458-943a4d80-f475-11e8-8b2c-28d90a8bd0c9.png)

**Comment by stdavis** [comment]
Possible config values:
* Phase field name
* Layer Indexes for each of the layers.

**Comment by stdavis** [comment]
Hey @msilski:

I'm having troubles correlating the layers in http://wfrc.maps.arcgis.com/home/webmap/viewer.html?webmap=07eb046bebab4791a084395c9362d52a with this mockup. Specifically, what layers map to the "Centers" and "Land Use Types" items in the mockup? Also, what about "Planning Boundaries"?

**Comment by msilski** [comment]
Sure thing. The data is not in an ideal configuration to match this filter tool, but as it is, "Centers" refers to these four types in "Regionally Significant Land Use":

- Metropolitan Center
- Regional Center
- Town Center
- Neighborhood Center

"Land Use Types" will eventually include our polygon open space dataset, which is not in the map. But as it is, "Land Use Types" refers to these types in "Regionally Significant Land Use":

- Employment District
- Industrial District
- Special District

And "Planning Boundaries" is the "Boundaries" dataset currently in the map.

**Comment by msilski** [comment]
If it's helpful, here is the REST endpoint for our best available open space dataset:

https://gis.wfrc.org/arcgis/rest/services/RTP19PS/LandUseA/MapServer/1

**Comment by stdavis** [comment]
![image](https://user-images.githubusercontent.com/1326248/49403386-e1365200-f709-11e8-860f-427e14e4d026.png)

**Comment by stdavis** [comment]
I haven't wired up anything yet, but here's how the layout is looking:
![image](https://user-images.githubusercontent.com/1326248/49447895-de347380-f794-11e8-8ba4-5247ef794ce8.png)

**Comment by stdavis** [comment]
Waiting on a new web map from @msilski...

**Comment by msilski** [comment]
After discussing with Bert, here is a revised mockup of the Filter widget:

![widget mockup](https://user-images.githubusercontent.com/1699870/49819400-908aae80-fd32-11e8-95df-130e91ef2376.png)

Summary of Edits:
- In Project Modes, Bike Ped has been changed to "Bike/Ped"
- The Project Phasing (colors) heading has been changed to "Phasing (colors)"
- The Centers heading has been changed to "Land Use"
- The radio buttons below the Land Use heading have been changed to three check boxes: _(filter by phasing)_, Centers, and General Land Use. The _(filter by phasing)_ is intended to replace the radio button functionality of toggling (now) Centers and General Land Use to use the indicated phasing. I am open to a better solution than a checkbox, maybe text next to "Land Use" that the user can click to toggle the filtering of phasing.
- The General Land Use symbol borrows the symbol set for Land Use Types, but now has a fourth color swatch
- The items in the Other heading have been reordered
- The symbol for Neighboring Projects is now a line instead of a box
- In the Other heading, Land Use Types has been replaced by "Neighboring Land Use" and uses the box symbol previously used in Neighboring Projects
- The color of the symbol for Planning Boundaries has been lightened

**Comment by msilski** [comment]
Here is a Google Sheet with a key matching layers in the web map to the above revised filter widget:

https://drive.google.com/open?id=1CaMtQzCAKHTyewZBNyw0S4xqu7_5r0WxPgUzVPSpq0o

Let me know if there is anything unclear about the layers or definition queries.

**Comment by stdavis** [comment]
The spreadsheet and updated mockup with comments is very helpful. Thanks!

What checkboxes would you like checked by default?

**Comment by msilski** [comment]
I will have to take a look at the release, but the checkboxes checked in the revised mockup are the ones we would like to have checked.

If down the road, we would like different checkboxes checked on/off by default, what would the process be like to make those changes? Would it be a code change or config change?

**Comment by stdavis** [comment]
OK. I will go with the latest mockup for default layer visibility.

> If down the road, we would like different checkboxes checked on/off by default, what would the process be like to make those changes? Would it be a code change or config change?

It's a code change at the moment. But we could make it configurable in the future if you'd like.

**Comment by stdavis** [comment]
@msilski Any feedback on the filter widget? Can I close this issue?

**Comment by msilski** [comment]
I'm hoping to test it in our new web application ([http://wfrc.org/rtp-2019-draft/]) this week. I should have feedback for you soon.

**Comment by stdavis** [comment]
Waiting on @msilski to add some new layers to the web map and the [config spreadsheet](https://drive.google.com/open?id=1CaMtQzCAKHTyewZBNyw0S4xqu7_5r0WxPgUzVPSpq0o).

**Comment by msilski** [comment]
I added the three MAG layers to the web maps to the Google Sheet (changes shown in red text). I also modified the names of Neighboring Points, Neighboring Lines, and MAG Point Projects to match the naming of the other layers.

**Comment by stdavis** [comment]
Hey @msilski I just pushed v1.4.1 which contains the fixes for the layer name default config values. I already had the MAG layers in widget. Let me know if you see any issues. I've also pushed a new release to http://test.mapserv.utah.gov/wfrctests/.

**Comment by msilski** [comment]
Thanks! I am working on a new web [application](https://wfrc.org/rtp-2019-adopted) that will use the filter widget. I will let you know if I encounter any issues.
